version: '3'
services:
  jable-downloader-service:
    container_name: jable-downloader-service
    build: 
      context: .
    volumes:
      - ./downloads:/app/downloads
      - ./db:/app/db

  jable-downloader-ui:
    container_name: jable-downloader-ui
    build: 
      context: ./client
    environment:
      - API_ENDPOINT="http://jable-downloader-service:3000"
    ports:
      - 41056:80
